'use client';

import { motion } from "framer-motion";
import styles from "../styles";
import Image from "next/image";
import Link from "next/link";
import { fadeIn, staggerContainer } from "../utils/motion";
import { TypingText } from "../components";
import { ArrowDownIcon } from "@heroicons/react/24/solid";

type Props = {}

function About({}: Props) {
  return (
    <section className={`${styles.paddings} relative z-10 -mt-32 sm:-mt-40 md:-mt-56`}>
      <div className="gradient-02 z-0" />
      <motion.div
        variants={staggerContainer as any}
        initial="hidden"
        whileInView="show"
        viewport={{ once: false, amount: 0.25 }}
        className={`${styles.innerWidth} mx-auto ${styles.flexCenter} flex-col`}
      >
        <TypingText title="| About Midjourney" textStyles="text-center" />
        <motion.p
          variants={fadeIn('up', 'tween', 0.2, 1)}
          className="mt-[8px] font-normal text-[20px] sm:text-[32px] text-center text-secondary-white"
        >
          <span className="font-extrabold text-white">Midjourney </span>
          is an AI art generator that creates 
          <span className="font-extrabold text-white"> unique digital art pieces </span>
          using machine learning algorithms. The system is trained on a dataset of images and can generate new images that are similar in style to the training set. The generated art can be used for various purposes such as digital wallpaper, desktop backgrounds, or as an addition to a website or application. Midjourney is built on top of GPT-3 as well as other machine learning models, it is able to generate not just images but also 
          <span className="font-extrabold text-white"> videos, animations, and 3D models. </span>
          The artwork generated by Midjourney is unique and can be used for commercial and non-commercial purposes. However, since it is based on the work of other artists, it is important to give credit to the original sources when using the generated artwork.
        </motion.p>
        <motion.div variants={fadeIn('up', 'tween', 0.3, 1)} >
          <ArrowDownIcon className="text-white w-[18px] h-[28px] sm:w-[36px] md:h-[56px] object-contain mt-[28px]"  />
        </motion.div>
      </motion.div>
    </section>
  )
}

export default About